name: Deploy Smart Home API BY PUPAN (Self-hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Docker container
        run: |
          cd /home/pupan/smart-home-api/xiomi-smarthome

          echo "STOP OLD"
          docker stop smart-home-api || true
          docker rm smart-home-api || true

          echo "UPDATE CODE"
          git fetch origin
          git reset --hard origin/main

          echo "REMOVE OLD IMAGE"
          docker rmi smart-home-api:latest || true

          echo "BUILD"
          docker build --no-cache -t smart-home-api .

          echo "RUN"
          docker run -d \
            -p 8112:5555 \
            --restart always \
            --env-file .env \
            --name smart-home-api \
            smart-home-api
